name: Release @zazos-team/vue-quill

on:
  push:
    branches:
      - alpha
      - beta
      - master
    paths:
      - 'packages/vue-quill/**'
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install root deps
        run: npm ci
      - name: Install package deps
        working-directory: packages/vue-quill
        run: npm ci
      - name: Release package
        working-directory: packages/vue-quill
        run: npx ts-node ../../scripts/release.ts vue-quill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
